import { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navigation
    dashboard: "Dashboard",
    analytics: "Analytics",
    history: "History",
    qrCodes: "QR Codes",
    staffView: "Staff View",
    report: "+ Report",
    signOut: "Sign Out",

    // Headline parts
    headline1: "Every second",
    headline2: "counts.",
    headline3: "Don't",
    headline4: "waste any.",

    // Feature titles and descriptions
    feature1Title: "Instant Detection",
    feature1Desc: "Guest scans QR, selects crisis. Gemini classifies severity and generates staff briefing in under 2 seconds.",
    feature2Title: "Live Coordination",
    feature2Desc: "Real-time venue map with crisis pins. Auto-assigned responders. Every staff member sees the same picture.",
    feature3Title: "EMS Handoff",
    feature3Desc: "One tap sends a structured briefing to emergency services. No verbal relay. No information loss.",
    feature4Title: "Post-Incident AI",
    feature4Desc: "AI-generated reports. Analytics dashboard. Guest feedback. Every crisis makes the system smarter.",


    // Landing
    tagline: "Every second counts. Don't waste any.",
    description: "AI-powered crisis coordination that eliminates fragmented communication between guests, staff, and emergency services.",
    reportEmergency: "Report Emergency",
    staffDashboard: "Staff Dashboard →",
    staffLogin: "Staff Login",
    avgResponse: "Avg response",
    geminiPowered: "Gemini powered",
    monitoring: "Monitoring",
    infoLost: "Info lost",
    howItWorks: "HOW IT WORKS",
    builtForWorst: "Built for the worst moments",
    readyToRespond: "Ready to respond faster?",
    demoSystem: "Demo the full system right now.",
    tryGuestButton: "Try Guest Panic Button",
    openCommandCenter: "Open Command Center",

    // Guest Report
    hotelTag: "BYTE CLUB PVT LTD · EMERGENCY",
    whoAreYou: "Who are you?",
    whatsHappening: "What's happening?",
    helpUsFindYou: "Help us find you faster",
    chooseEmergency: "Choose the type of emergency",
    yourName: "YOUR NAME (OPTIONAL)",
    roomNumber: "ROOM NUMBER *",
    namePlaceholder: "e.g. Rahul Sharma",
    roomPlaceholder: "e.g. 814",
    continue: "Continue →",
    describeSituation: "DESCRIBE THE SITUATION",
    describePlaceholder: "Tell us what's happening...",
    back: "← Back",
    sendAlert: "SEND ALERT",
    alertingStaff: "Alerting staff...",
    helpOnWay: "Help is on the way",
    staffNotified: "Staff have been notified and are responding. Stay calm and remain in your room.",
    emergencyContacts: "EMERGENCY CONTACTS",
    reception: "Reception",
    nationalEmergency: "National Emergency",

    // Crisis types
    medical: "Medical",
    medicalDesc: "Injury or illness",
    fire: "Fire",
    fireDesc: "Fire or smoke",
    security: "Security",
    securityDesc: "Threat or intrusion",
    flood: "Flood",
    floodDesc: "Water or leak",
    panic: "Panic",
    panicDesc: "General distress",
    other: "Other",
    otherDesc: "Something else",

    // Dashboard
    commandCenter: "Command Center",
    live: "Live",
    active: "ACTIVE",
    activeLabel: "Active",
    resolvedLabel: "Resolved",
    total: "Total",
    noIncidents: "No active incidents",
    selectIncident: "Select an incident to view details",
    aiBriefing: "GEMINI AI BRIEFING",
    responders: "RESPONDERS",
    responseEta: "RESPONSE ETA",
    severity: "SEVERITY",
    guestMessage: "GUEST MESSAGE",
    aiReport: "AI INCIDENT REPORT",
    generateAI: "Generate with AI ◆",
    generating: "Generating...",
    markResolved: "Mark Resolved ✓",
    resolving: "Resolving...",
    tapToView: "Tap to view details →",
    backToList: "← Back to list",
    min: "min",

    // Login
    staffAccess: "BYTE CLUB PVT LTD · STAFF ACCESS",
    staffLogin2: "Staff Login",
    accessCrisis: "Access the crisis command center",
    email: "EMAIL",
    password: "PASSWORD",
    signingIn: "Signing in...",
    signIn: "Sign In →",
    fillFields: "Please fill all fields",
    invalidCredentials: "Invalid email or password",

    // Feedback
    howDidWeDo: "How did we do?",
    incidentResolved: "Your incident has been resolved. We'd love your feedback.",
    rateExperience: "RATE YOUR EXPERIENCE",
    additionalComments: "ADDITIONAL COMMENTS",
    commentsPlaceholder: "Tell us more about your experience...",
    submitFeedback: "Submit Feedback",
    submitting: "Submitting...",
    thankYou: "Thank You",
    feedbackHelps: "Your feedback helps us improve our emergency response for every guest.",
    staffFast: "Staff was fast",
    staffHelpful: "Staff was helpful",
    feltSafe: "Felt safe",
    clearComms: "Clear communication",
    poor: "Poor",
    fair: "Fair",
    good: "Good",
    great: "Great",
    excellent: "Excellent!",

    // Responder
    responderView: "Responder View",
    myAlerts: "My Alerts",
    allClear: "All clear",
    noActiveIncidents: "No active incidents",
    needResponse: "incident needs response",
    needResponsePlural: "incidents need response",
    immediateAction: "⚡ YOUR IMMEDIATE ACTION",
    guestInfo: "GUEST INFO",
    room: "Room",
    guest: "Guest",
    eta: "ETA",
    callEmergency: "📞 Call 112 Emergency",
    markAsResolved: "Mark as Resolved ✓",
  },

  hi: {
    dashboard: "डैशबोर्ड",
    analytics: "विश्लेषण",
    history: "इतिहास",
    qrCodes: "QR कोड",
    staffView: "स्टाफ व्यू",
    report: "+ रिपोर्ट",
    signOut: "साइन आउट",
    tagline: "हर सेकंड मायने रखता है। एक भी बर्बाद मत करो।",
    description: "AI-संचालित संकट समन्वय जो मेहमानों, कर्मचारियों और आपातकालीन सेवाओं के बीच संचार को एकीकृत करता है।",
    reportEmergency: "आपातकाल रिपोर्ट करें",
    staffDashboard: "स्टाff डैशबोर्ड →",
    staffLogin: "स्टाफ लॉगिन",
    avgResponse: "औसत प्रतिक्रिया",
    geminiPowered: "Gemini संचालित",
    monitoring: "निगरानी",
    infoLost: "जानकारी खोई",
    howItWorks: "यह कैसे काम करता है",
    builtForWorst: "सबसे बुरे पलों के लिए बनाया गया",
    readyToRespond: "तेज़ी से जवाब देने के लिए तैयार?",
    demoSystem: "अभी पूरे सिस्टम का डेमो करें।",
    tryGuestButton: "गेस्ट पैनिक बटन आज़माएं",
    openCommandCenter: "कमांड सेंटर खोलें",
    hotelTag: "बाइट क्लब प्राइवेट लिमिटेड · आपातकाल",
    whoAreYou: "आप कौन हैं?",
    whatsHappening: "क्या हो रहा है?",
    helpUsFindYou: "हमें आपको जल्दी खोजने में मदद करें",
    chooseEmergency: "आपातकाल का प्रकार चुनें",
    yourName: "आपका नाम (वैकल्पिक)",
    roomNumber: "कमरा नंबर *",
    namePlaceholder: "जैसे राहुल शर्मा",
    roomPlaceholder: "जैसे 814",
    continue: "जारी रखें →",
    describeSituation: "स्थिति का वर्णन करें",
    describePlaceholder: "बताएं क्या हो रहा है...",
    back: "← वापस",
    sendAlert: "अलर्ट भेजें",
    alertingStaff: "स्टाफ को सतर्क कर रहे हैं...",
    helpOnWay: "मदद आ रही है",
    staffNotified: "स्टाफ को सूचित कर दिया गया है और वे प्रतिक्रिया दे रहे हैं। शांत रहें और अपने कमरे में रहें।",
    emergencyContacts: "आपातकालीन संपर्क",
    reception: "रिसेप्शन",
    nationalEmergency: "राष्ट्रीय आपातकाल",
    medical: "चिकित्सा",
    medicalDesc: "चोट या बीमारी",
    fire: "आग",
    fireDesc: "आग या धुआं",
    security: "सुरक्षा",
    securityDesc: "खतरा या घुसपैठ",
    flood: "बाढ़",
    floodDesc: "पानी या रिसाव",
    panic: "घबराहट",
    panicDesc: "सामान्य संकट",
    other: "अन्य",
    otherDesc: "कुछ और",
    commandCenter: "कमांड सेंटर",
    live: "लाइव",
    active: "सक्रिय",
    activeLabel: "सक्रिय",
    resolvedLabel: "हल किया",
    total: "कुल",
    noIncidents: "कोई सक्रिय घटना नहीं",
    selectIncident: "विवरण देखने के लिए घटना चुनें",
    aiBriefing: "GEMINI AI ब्रीफिंग",
    responders: "प्रतिक्रियाकर्ता",
    responseEta: "प्रतिक्रिया समय",
    severity: "गंभीरता",
    guestMessage: "अतिथि संदेश",
    aiReport: "AI घटना रिपोर्ट",
    generateAI: "AI से उत्पन्न करें ◆",
    generating: "उत्पन्न हो रहा है...",
    markResolved: "हल हुआ ✓",
    resolving: "हल हो रहा है...",
    tapToView: "विवरण देखने के लिए टैप करें →",
    backToList: "← सूची पर वापस",
    min: "मिनट",
    staffAccess: "बाइट क्लब · स्टाफ एक्सेस",
    staffLogin2: "स्टाफ लॉगिन",
    accessCrisis: "संकट कमांड सेंटर तक पहुंचें",
    email: "ईमेल",
    password: "पासवर्ड",
    signingIn: "साइन इन हो रहा है...",
    signIn: "साइन इन →",
    fillFields: "कृपया सभी फ़ील्ड भरें",
    invalidCredentials: "अमान्य ईमेल या पासवर्ड",
    howDidWeDo: "हमने कैसा किया?",
    incidentResolved: "आपकी घटना हल हो गई है। हम आपकी प्रतिक्रिया चाहते हैं।",
    rateExperience: "अपना अनुभव रेट करें",
    additionalComments: "अतिरिक्त टिप्पणियां",
    commentsPlaceholder: "अपने अनुभव के बारे में और बताएं...",
    submitFeedback: "प्रतिक्रिया जमा करें",
    submitting: "जमा हो रहा है...",
    thankYou: "धन्यवाद",
    feedbackHelps: "आपकी प्रतिक्रिया हमें हर अतिथि के लिए आपातकालीन प्रतिक्रिया सुधारने में मदद करती है।",
    staffFast: "स्टाफ तेज़ था",
    staffHelpful: "स्टाफ सहायक था",
    feltSafe: "सुरक्षित महसूस किया",
    clearComms: "स्पष्ट संचार",
    poor: "खराब",
    fair: "ठीक",
    good: "अच्छा",
    great: "बढ़िया",
    excellent: "उत्कृष्ट!",
    responderView: "प्रतिक्रियाकर्ता व्यू",
    myAlerts: "मेरे अलर्ट",
    allClear: "सब ठीक है",
    noActiveIncidents: "कोई सक्रिय घटना नहीं",
    needResponse: "घटना को प्रतिक्रिया चाहिए",
    needResponsePlural: "घटनाओं को प्रतिक्रिया चाहिए",
    immediateAction: "⚡ तत्काल कार्रवाई",
    guestInfo: "अतिथि जानकारी",
    room: "कमरा",
    guest: "अतिथि",
    eta: "अनुमानित समय",
    callEmergency: "📞 112 पर कॉल करें",
    markAsResolved: "हल हुआ ✓",
    headline1: "हर सेकंड",
    headline2: "मायने रखता है।",
    headline3: "एक भी",
    headline4: "बर्बाद मत करो।",
    feature1Title: "तत्काल पहचान",
    feature1Desc: "अतिथि QR स्कैन करता है, संकट चुनता है। Gemini 2 सेकंड में गंभीरता वर्गीकृत करता है।",
    feature2Title: "लाइव समन्वय",
    feature2Desc: "संकट पिन के साथ रीयल-टाइम वेन्यू मैप। स्वचालित रूप से असाइन किए गए प्रतिक्रियाकर्ता।",
    feature3Title: "EMS हैंडऑफ",
    feature3Desc: "एक टैप से आपातकालीन सेवाओं को संरचित ब्रीफिंग भेजता है। कोई मौखिक रिले नहीं।",
    feature4Title: "घटना के बाद AI",
    feature4Desc: "AI-जनित रिपोर्ट। एनालिटिक्स डैशबोर्ड। अतिथि प्रतिक्रिया। हर संकट सिस्टम को स्मार्ट बनाता है।",
  },

  bn: {
    dashboard: "ড্যাশবোর্ড",
    analytics: "বিশ্লেষণ",
    history: "ইতিহাস",
    qrCodes: "QR কোড",
    staffView: "স্টাফ ভিউ",
    report: "+ রিপোর্ট",
    signOut: "সাইন আউট",
    tagline: "প্রতিটি সেকেন্ড গুরুত্বপূর্ণ। একটিও নষ্ট করবেন না।",
    description: "AI-চালিত সংকট সমন্বয় যা অতিথি, কর্মী এবং জরুরি সেবার মধ্যে যোগাযোগ নিশ্চিত করে।",
    reportEmergency: "জরুরি অবস্থা রিপোর্ট করুন",
    staffDashboard: "স্টাফ ড্যাশবোর্ড →",
    staffLogin: "স্টাফ লগইন",
    avgResponse: "গড় প্রতিক্রিয়া",
    geminiPowered: "Gemini চালিত",
    monitoring: "পর্যবেক্ষণ",
    infoLost: "তথ্য হারানো",
    howItWorks: "এটি কীভাবে কাজ করে",
    builtForWorst: "সবচেয়ে খারাপ মুহূর্তের জন্য তৈরি",
    readyToRespond: "দ্রুত সাড়া দিতে প্রস্তুত?",
    demoSystem: "এখনই সম্পূর্ণ সিস্টেম ডেমো করুন।",
    tryGuestButton: "গেস্ট প্যানিক বাটন ব্যবহার করুন",
    openCommandCenter: "কমান্ড সেন্টার খুলুন",
    hotelTag: "বাইট ক্লাব প্রাইভেট লিমিটেড · জরুরি",
    whoAreYou: "আপনি কে?",
    whatsHappening: "কী হচ্ছে?",
    helpUsFindYou: "আমাদের আপনাকে দ্রুত খুঁজে পেতে সাহায্য করুন",
    chooseEmergency: "জরুরি অবস্থার ধরন বেছে নিন",
    yourName: "আপনার নাম (ঐচ্ছিক)",
    roomNumber: "রুম নম্বর *",
    namePlaceholder: "যেমন রাহুল শর্মা",
    roomPlaceholder: "যেমন 814",
    continue: "চালিয়ে যান →",
    describeSituation: "পরিস্থিতি বর্ণনা করুন",
    describePlaceholder: "কী হচ্ছে তা বলুন...",
    back: "← পিছনে",
    sendAlert: "অ্যালার্ট পাঠান",
    alertingStaff: "স্টাফকে সতর্ক করা হচ্ছে...",
    helpOnWay: "সাহায্য আসছে",
    staffNotified: "স্টাফকে জানানো হয়েছে এবং তারা সাড়া দিচ্ছে। শান্ত থাকুন এবং আপনার রুমে থাকুন।",
    emergencyContacts: "জরুরি যোগাযোগ",
    reception: "রিসেপশন",
    nationalEmergency: "জাতীয় জরুরি",
    medical: "চিকিৎসা",
    medicalDesc: "আঘাত বা অসুস্থতা",
    fire: "আগুন",
    fireDesc: "আগুন বা ধোঁয়া",
    security: "নিরাপত্তা",
    securityDesc: "হুমকি বা অনুপ্রবেশ",
    flood: "বন্যা",
    floodDesc: "পানি বা লিক",
    panic: "আতঙ্ক",
    panicDesc: "সাধারণ সংকট",
    other: "অন্যান্য",
    otherDesc: "অন্য কিছু",
    commandCenter: "কমান্ড সেন্টার",
    live: "লাইভ",
    active: "সক্রিয়",
    activeLabel: "সক্রিয়",
    resolvedLabel: "সমাধান হয়েছে",
    total: "মোট",
    noIncidents: "কোনো সক্রিয় ঘটনা নেই",
    selectIncident: "বিবরণ দেখতে ঘটনা নির্বাচন করুন",
    aiBriefing: "GEMINI AI ব্রিফিং",
    responders: "প্রতিক্রিয়াকারী",
    responseEta: "প্রতিক্রিয়া সময়",
    severity: "তীব্রতা",
    guestMessage: "অতিথি বার্তা",
    aiReport: "AI ঘটনা রিপোর্ট",
    generateAI: "AI দিয়ে তৈরি করুন ◆",
    generating: "তৈরি হচ্ছে...",
    markResolved: "সমাধান হয়েছে ✓",
    resolving: "সমাধান হচ্ছে...",
    tapToView: "বিবরণ দেখতে ট্যাপ করুন →",
    backToList: "← তালিকায় ফিরুন",
    min: "মিনিট",
    staffAccess: "বাইট ক্লাব · স্টাফ অ্যাক্সেস",
    staffLogin2: "স্টাফ লগইন",
    accessCrisis: "সংকট কমান্ড সেন্টারে প্রবেশ করুন",
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    signingIn: "সাইন ইন হচ্ছে...",
    signIn: "সাইন ইন →",
    fillFields: "সমস্ত ফিল্ড পূরণ করুন",
    invalidCredentials: "অবৈধ ইমেইল বা পাসওয়ার্ড",
    howDidWeDo: "আমরা কেমন করলাম?",
    incidentResolved: "আপনার ঘটনা সমাধান হয়েছে। আমরা আপনার মতামত চাই।",
    rateExperience: "আপনার অভিজ্ঞতা রেট করুন",
    additionalComments: "অতিরিক্ত মন্তব্য",
    commentsPlaceholder: "আপনার অভিজ্ঞতা সম্পর্কে আরও বলুন...",
    submitFeedback: "মতামত জমা দিন",
    submitting: "জমা হচ্ছে...",
    thankYou: "ধন্যবাদ",
    feedbackHelps: "আপনার মতামত আমাদের প্রতিটি অতিথির জন্য জরুরি প্রতিক্রিয়া উন্নত করতে সাহায্য করে।",
    staffFast: "স্টাফ দ্রুত ছিল",
    staffHelpful: "স্টাফ সহায়ক ছিল",
    feltSafe: "নিরাপদ অনুভব করেছি",
    clearComms: "স্পষ্ট যোগাযোগ",
    poor: "খারাপ",
    fair: "ঠিক আছে",
    good: "ভালো",
    great: "দারুণ",
    excellent: "অসাধারণ!",
    responderView: "প্রতিক্রিয়াকারী ভিউ",
    myAlerts: "আমার অ্যালার্ট",
    allClear: "সব ঠিক আছে",
    noActiveIncidents: "কোনো সক্রিয় ঘটনা নেই",
    needResponse: "ঘটনার প্রতিক্রিয়া দরকার",
    needResponsePlural: "ঘটনার প্রতিক্রিয়া দরকার",
    immediateAction: "⚡ তাৎক্ষণিক পদক্ষেপ",
    guestInfo: "অতিথি তথ্য",
    room: "রুম",
    guest: "অতিথি",
    eta: "আনুমানিক সময়",
    callEmergency: "📞 112 কল করুন",
    markAsResolved: "সমাধান হয়েছে ✓",
    headline1: "প্রতিটি সেকেন্ড",
    headline2: "গুরুত্বপূর্ণ।",
    headline3: "একটিও",
    headline4: "নষ্ট করবেন না।",
    feature1Title: "তাৎক্ষণিক সনাক্তকরণ",
    feature1Desc: "অতিথি QR স্ক্যান করেন, সংকট বেছে নেন। Gemini ২ সেকেন্ডে তীব্রতা শ্রেণীবদ্ধ করে।",
    feature2Title: "লাইভ সমন্বয়",
    feature2Desc: "ক্রাইসিস পিন সহ রিয়েল-টাইম ভেন্যু ম্যাপ। স্বয়ংক্রিয়ভাবে নিযুক্ত প্রতিক্রিয়াকারী।",
    feature3Title: "EMS হ্যান্ডঅফ",
    feature3Desc: "এক ট্যাপে জরুরি সেবায় কাঠামোগত ব্রিফিং পাঠায়। কোনো মৌখিক রিলে নেই।",
    feature4Title: "ঘটনা পরবর্তী AI",
    feature4Desc: "AI-জেনারেটেড রিপোর্ট। অ্যানালিটিক্স ড্যাশবোর্ড। অতিথির মতামত।",
  },

  ta: {
    dashboard: "டாஷ்போர்டு",
    analytics: "பகுப்பாய்வு",
    history: "வரலாறு",
    qrCodes: "QR குறியீடுகள்",
    staffView: "ஊழியர் காட்சி",
    report: "+ அறிக்கை",
    signOut: "வெளியேறு",
    tagline: "ஒவ்வொரு நொடியும் முக்கியம். எதையும் வீணாக்காதீர்கள்.",
    description: "விருந்தினர்கள், ஊழியர்கள் மற்றும் அவசர சேவைகளுக்கு இடையே தகவல்தொடர்பை ஒருங்கிணைக்கும் AI-இயங்கும் நெருக்கடி ஒருங்கிணைப்பு.",
    reportEmergency: "அவசரநிலை அறிக்கை",
    staffDashboard: "ஊழியர் டாஷ்போர்டு →",
    staffLogin: "ஊழியர் உள்நுழைவு",
    avgResponse: "சராசரி பதில்",
    geminiPowered: "Gemini இயக்கம்",
    monitoring: "கண்காணிப்பு",
    infoLost: "தகவல் இழப்பு",
    howItWorks: "இது எப்படி செயல்படுகிறது",
    builtForWorst: "மோசமான தருணங்களுக்காக கட்டப்பட்டது",
    readyToRespond: "வேகமாக பதிலளிக்க தயாரா?",
    demoSystem: "இப்போதே முழு அமைப்பையும் பார்க்கவும்.",
    tryGuestButton: "விருந்தினர் பேனிக் பட்டனை முயற்சிக்கவும்",
    openCommandCenter: "கட்டளை மையத்தை திறக்கவும்",
    hotelTag: "பைட் க்ளப் · அவசரநிலை",
    whoAreYou: "நீங்கள் யார்?",
    whatsHappening: "என்ன நடக்கிறது?",
    helpUsFindYou: "உங்களை விரைவாக கண்டுபிடிக்க உதவுங்கள்",
    chooseEmergency: "அவசரநிலையின் வகையை தேர்ந்தெடுக்கவும்",
    yourName: "உங்கள் பெயர் (விருப்பம்)",
    roomNumber: "அறை எண் *",
    namePlaceholder: "எ.கா. ராகுல் சர்மா",
    roomPlaceholder: "எ.கா. 814",
    continue: "தொடரவும் →",
    describeSituation: "சூழ்நிலையை விவரிக்கவும்",
    describePlaceholder: "என்ன நடக்கிறது என்று சொல்லுங்கள்...",
    back: "← பின்னே",
    sendAlert: "எச்சரிக்கை அனுப்பு",
    alertingStaff: "ஊழியர்களை எச்சரிக்கிறது...",
    helpOnWay: "உதவி வருகிறது",
    staffNotified: "ஊழியர்களுக்கு தெரிவிக்கப்பட்டது. அமைதியாக இருங்கள் மற்றும் உங்கள் அறையில் இருங்கள்.",
    emergencyContacts: "அவசர தொடர்புகள்",
    reception: "வரவேற்பு",
    nationalEmergency: "தேசிய அவசரநிலை",
    medical: "மருத்துவம்",
    medicalDesc: "காயம் அல்லது நோய்",
    fire: "தீ",
    fireDesc: "தீ அல்லது புகை",
    security: "பாதுகாப்பு",
    securityDesc: "அச்சுறுத்தல் அல்லது ஊடுருவல்",
    flood: "வெள்ளம்",
    floodDesc: "தண்ணீர் அல்லது கசிவு",
    panic: "பதட்டம்",
    panicDesc: "பொது நெருக்கடி",
    other: "மற்றவை",
    otherDesc: "வேறு ஏதாவது",
    commandCenter: "கட்டளை மையம்",
    live: "நேரடி",
    active: "செயலில்",
    activeLabel: "செயலில்",
    resolvedLabel: "தீர்க்கப்பட்டது",
    total: "மொத்தம்",
    noIncidents: "செயலில் உள்ள சம்பவங்கள் இல்லை",
    selectIncident: "விவரங்களைக் காண சம்பவத்தை தேர்ந்தெடுக்கவும்",
    aiBriefing: "GEMINI AI விளக்கம்",
    responders: "பதிலளிப்பவர்கள்",
    responseEta: "பதில் நேரம்",
    severity: "தீவிரம்",
    guestMessage: "விருந்தினர் செய்தி",
    aiReport: "AI சம்பவ அறிக்கை",
    generateAI: "AI மூலம் உருவாக்கு ◆",
    generating: "உருவாக்குகிறது...",
    markResolved: "தீர்க்கப்பட்டது ✓",
    resolving: "தீர்க்கப்படுகிறது...",
    tapToView: "விவரங்களைக் காண தட்டவும் →",
    backToList: "← பட்டியலுக்கு திரும்பு",
    min: "நிமிடம்",
    staffAccess: "பைட் க்ளப் · ஊழியர் அணுகல்",
    staffLogin2: "ஊழியர் உள்நுழைவு",
    accessCrisis: "நெருக்கடி கட்டளை மையத்தை அணுகவும்",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    signingIn: "உள்நுழைகிறது...",
    signIn: "உள்நுழைக →",
    fillFields: "அனைத்து புலங்களையும் நிரப்பவும்",
    invalidCredentials: "தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்",
    howDidWeDo: "நாங்கள் எப்படி செய்தோம்?",
    incidentResolved: "உங்கள் சம்பவம் தீர்க்கப்பட்டது. உங்கள் கருத்து வேண்டும்.",
    rateExperience: "உங்கள் அனுபவத்தை மதிப்பிடுங்கள்",
    additionalComments: "கூடுதல் கருத்துகள்",
    commentsPlaceholder: "உங்கள் அனுபவத்தைப் பற்றி மேலும் சொல்லுங்கள்...",
    submitFeedback: "கருத்தை சமர்ப்பிக்கவும்",
    submitting: "சமர்ப்பிக்கிறது...",
    thankYou: "நன்றி",
    feedbackHelps: "உங்கள் கருத்து ஒவ்வொரு விருந்தினருக்கும் அவசர பதிலை மேம்படுத்த உதவுகிறது.",
    staffFast: "ஊழியர் வேகமாக இருந்தனர்",
    staffHelpful: "ஊழியர் உதவிகரமாக இருந்தனர்",
    feltSafe: "பாதுகாப்பாக உணர்ந்தேன்",
    clearComms: "தெளிவான தகவல்தொடர்பு",
    poor: "மோசம்",
    fair: "சரி",
    good: "நல்லது",
    great: "சிறந்தது",
    excellent: "அருமை!",
    responderView: "பதிலளிப்பவர் காட்சி",
    myAlerts: "என் எச்சரிக்கைகள்",
    allClear: "அனைத்தும் சரி",
    noActiveIncidents: "செயலில் உள்ள சம்பவங்கள் இல்லை",
    needResponse: "சம்பவத்திற்கு பதில் தேவை",
    needResponsePlural: "சம்பவங்களுக்கு பதில் தேவை",
    immediateAction: "⚡ உடனடி நடவடிக்கை",
    guestInfo: "விருந்தினர் தகவல்",
    room: "அறை",
    guest: "விருந்தினர்",
    eta: "மதிப்பிடப்பட்ட நேரம்",
    callEmergency: "📞 112 அழைக்கவும்",
    markAsResolved: "தீர்க்கப்பட்டது ✓",
    headline1: "ஒவ்வொரு நொடியும்",
    headline2: "முக்கியம்.",
    headline3: "எதையும்",
    headline4: "வீணாக்காதீர்கள்.",
    feature1Title: "உடனடி கண்டறிதல்",
    feature1Desc: "விருந்தினர் QR ஸ்கேன் செய்கிறார், நெருக்கடியை தேர்ந்தெடுக்கிறார். Gemini 2 வினாடியில் தீவிரத்தை வகைப்படுத்துகிறது.",
    feature2Title: "நேரடி ஒருங்கிணைப்பு",
    feature2Desc: "நெருக்கடி பின்களுடன் நிகழ்நேர வேதி வரைபடம். தானாக நியமிக்கப்பட்ட பதிலளிப்பவர்கள்.",
    feature3Title: "EMS கைமாற்றம்",
    feature3Desc: "ஒரு தட்டுதலில் அவசர சேவைகளுக்கு கட்டமைக்கப்பட்ட விளக்கம் அனுப்புகிறது.",
    feature4Title: "சம்பவத்திற்கு பிந்தைய AI",
    feature4Desc: "AI-உருவாக்கிய அறிக்கைகள். பகுப்பாய்வு டாஷ்போர்டு. விருந்தினர் கருத்து.",
  },

  te: {
    dashboard: "డాష్‌బోర్డ్",
    analytics: "విశ్లేషణ",
    history: "చరిత్ర",
    qrCodes: "QR కోడ్‌లు",
    staffView: "స్టాఫ్ వ్యూ",
    report: "+ నివేదిక",
    signOut: "సైన్ అవుట్",
    tagline: "ప్రతి సెకనూ ముఖ్యమైనది. ఒక్కటీ వృధా చేయకండి.",
    description: "అతిథులు, సిబ్బంది మరియు అత్యవసర సేవల మధ్య సమన్వయాన్ని నిర్ధారించే AI-ఆధారిత సంక్షోభ సమన్వయం.",
    reportEmergency: "అత్యవసర నివేదిక",
    staffDashboard: "స్టాఫ్ డాష్‌బోర్డ్ →",
    staffLogin: "స్టాఫ్ లాగిన్",
    avgResponse: "సగటు ప్రతిస్పందన",
    geminiPowered: "Gemini ఆధారిత",
    monitoring: "పర్యవేక్షణ",
    infoLost: "సమాచారం కోల్పోయింది",
    howItWorks: "ఇది ఎలా పనిచేస్తుంది",
    builtForWorst: "అత్యంత చెడు క్షణాల కోసం నిర్మించబడింది",
    readyToRespond: "వేగంగా స్పందించడానికి సిద్ధంగా ఉన్నారా?",
    demoSystem: "ఇప్పుడే పూర్తి సిస్టమ్‌ను డెమో చేయండి.",
    tryGuestButton: "గెస్ట్ పానిక్ బటన్ ప్రయత్నించండి",
    openCommandCenter: "కమాండ్ సెంటర్ తెరవండి",
    hotelTag: "బైట్ క్లబ్ · అత్యవసర",
    whoAreYou: "మీరు ఎవరు?",
    whatsHappening: "ఏమి జరుగుతోంది?",
    helpUsFindYou: "మిమ్మల్ని త్వరగా కనుగొనడానికి సహాయపడండి",
    chooseEmergency: "అత్యవసర రకాన్ని ఎంచుకోండి",
    yourName: "మీ పేరు (ఐచ్ఛికం)",
    roomNumber: "గది నంబర్ *",
    namePlaceholder: "ఉదా. రాహుల్ శర్మ",
    roomPlaceholder: "ఉదా. 814",
    continue: "కొనసాగించు →",
    describeSituation: "పరిస్థితిని వివరించండి",
    describePlaceholder: "ఏమి జరుగుతుందో చెప్పండి...",
    back: "← వెనక్కి",
    sendAlert: "హెచ్చరిక పంపండి",
    alertingStaff: "సిబ్బందిని హెచ్చరిస్తోంది...",
    helpOnWay: "సహాయం వస్తోంది",
    staffNotified: "సిబ్బందికి తెలియజేయబడింది మరియు వారు స్పందిస్తున్నారు. శాంతంగా ఉండండి మరియు మీ గదిలో ఉండండి.",
    emergencyContacts: "అత్యవసర పరిచయాలు",
    reception: "రిసెప్షన్",
    nationalEmergency: "జాతీయ అత్యవసర",
    medical: "వైద్య",
    medicalDesc: "గాయం లేదా అనారోగ్యం",
    fire: "అగ్ని",
    fireDesc: "అగ్ని లేదా పొగ",
    security: "భద్రత",
    securityDesc: "బెదిరింపు లేదా చొరబాటు",
    flood: "వరద",
    floodDesc: "నీరు లేదా లీకేజ్",
    panic: "భయం",
    panicDesc: "సాధారణ సంక్షోభం",
    other: "ఇతర",
    otherDesc: "వేరే ఏదైనా",
    commandCenter: "కమాండ్ సెంటర్",
    live: "లైవ్",
    active: "చురుకుగా",
    activeLabel: "చురుకుగా",
    resolvedLabel: "పరిష్కరించబడింది",
    total: "మొత్తం",
    noIncidents: "చురుకైన సంఘటనలు లేవు",
    selectIncident: "వివరాలు చూడటానికి సంఘటనను ఎంచుకోండి",
    aiBriefing: "GEMINI AI వివరణ",
    responders: "స్పందించేవారు",
    responseEta: "స్పందన సమయం",
    severity: "తీవ్రత",
    guestMessage: "అతిథి సందేశం",
    aiReport: "AI సంఘటన నివేదిక",
    generateAI: "AI తో రూపొందించు ◆",
    generating: "రూపొందిస్తోంది...",
    markResolved: "పరిష్కరించబడింది ✓",
    resolving: "పరిష్కరిస్తోంది...",
    tapToView: "వివరాలు చూడటానికి నొక్కండి →",
    backToList: "← జాబితాకు తిరిగి",
    min: "నిమిషం",
    staffAccess: "బైట్ క్లబ్ · స్టాఫ్ యాక్సెస్",
    staffLogin2: "స్టాఫ్ లాగిన్",
    accessCrisis: "సంక్షోభ కమాండ్ సెంటర్‌ను యాక్సెస్ చేయండి",
    email: "ఇమెయిల్",
    password: "పాస్‌వర్డ్",
    signingIn: "సైన్ ఇన్ అవుతోంది...",
    signIn: "సైన్ ఇన్ →",
    fillFields: "అన్ని ఫీల్డ్‌లను పూరించండి",
    invalidCredentials: "చెల్లని ఇమెయిల్ లేదా పాస్‌వర్డ్",
    howDidWeDo: "మేము ఎలా చేసాము?",
    incidentResolved: "మీ సంఘటన పరిష్కరించబడింది. మీ అభిప్రాయం కావాలి.",
    rateExperience: "మీ అనుభవాన్ని రేట్ చేయండి",
    additionalComments: "అదనపు వ్యాఖ్యలు",
    commentsPlaceholder: "మీ అనుభవం గురించి మరింత చెప్పండి...",
    submitFeedback: "అభిప్రాయం సమర్పించండి",
    submitting: "సమర్పిస్తోంది...",
    thankYou: "ధన్యవాదాలు",
    feedbackHelps: "మీ అభిప్రాయం ప్రతి అతిథికి అత్యవసర స్పందనను మెరుగుపరచడంలో సహాయపడుతుంది.",
    staffFast: "సిబ్బంది వేగంగా ఉన్నారు",
    staffHelpful: "సిబ్బంది సహాయకంగా ఉన్నారు",
    feltSafe: "సురక్షితంగా అనిపించింది",
    clearComms: "స్పష్టమైన సంభాషణ",
    poor: "చెడు",
    fair: "సరే",
    good: "మంచిది",
    great: "గొప్పది",
    excellent: "అద్భుతం!",
    responderView: "స్పందించేవారి వ్యూ",
    myAlerts: "నా హెచ్చరికలు",
    allClear: "అన్నీ సరే",
    noActiveIncidents: "చురుకైన సంఘటనలు లేవు",
    needResponse: "సంఘటనకు స్పందన అవసరం",
    needResponsePlural: "సంఘటనలకు స్పందన అవసరం",
    immediateAction: "⚡ తక్షణ చర్య",
    guestInfo: "అతిథి సమాచారం",
    room: "గది",
    guest: "అతిథి",
    eta: "అంచనా సమయం",
    callEmergency: "📞 112 కి కాల్ చేయండి",
    markAsResolved: "పరిష్కరించబడింది ✓",
    headline1: "ప్రతి సెకనూ",
    headline2: "ముఖ్యమైనది.",
    headline3: "ఒక్కటీ",
    headline4: "వృధా చేయకండి.",
    feature1Title: "తక్షణ గుర్తింపు",
    feature1Desc: "అతిథి QR స్కాన్ చేస్తారు, సంక్షోభం ఎంచుకుంటారు. Gemini 2 సెకన్లలో తీవ్రతను వర్గీకరిస్తుంది.",
    feature2Title: "లైవ్ సమన్వయం",
    feature2Desc: "క్రైసిస్ పిన్‌లతో రియల్-టైమ్ వేదిక మ్యాప్. స్వయంచాలకంగా కేటాయించిన స్పందించేవారు.",
    feature3Title: "EMS హ్యాండాఫ్",
    feature3Desc: "ఒక్క తాకడంతో అత్యవసర సేవలకు నిర్మాణాత్మక బ్రీఫింగ్ పంపుతుంది.",
    feature4Title: "సంఘటన తర్వాత AI",
    feature4Desc: "AI-రూపొందించిన నివేదికలు. అనలిటిక్స్ డాష్‌బోర్డ్. అతిథి అభిప్రాయం.",
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("nexus-language") || "en";
  });

  function changeLanguage(lang) {
    setLanguage(lang);
    localStorage.setItem("nexus-language", lang);
  }

  const t = translations[language] || translations.en;

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}